### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by xuxy09** [Lyken17/pytorch-OpCounter#61]
As far as I can understand, the direct output of the "profile" function is MACs instead of FLOPs. However, the demo code in the readme file uses flops as the name of the output variable. Is this a typo? Thanks.

**Comment by Lyken17** [comment]
Yes, your understanding is correct. I will update it later today.

Sent from my iPhone

On Jan 16, 2020, at 12:17, XiangyuXu <notifications@github.com<mailto:notifications@github.com>> wrote:


As far as I can understand, the direct output of the "profile" function is MACs instead of FLOPs. However, the demo code in the readme file uses flops as the name of the output variable. Is this a typo? Thanks.

**Comment by Lyken17** [comment]
fixed.
