### ISSUE TITLE
Calculation of trainable parameters is inaccurate due to storage as floating-point variable

### ISSUE THREAD

**Issue by felker** [Lyken17/pytorch-OpCounter#71]
I noticed this when testing out the module on a single, large `Linear()` layer:
```python
layer = torch.nn.Linear(8153, 7533, bias=False)
...
flops, params = profile(layer, inputs=(inputs,))
print(f"{flops} FLOPS    {params} parameters")
```
The tool returns:
```
843934466048.0 FLOPS    61416548.0 parameters
```
The latter figure is off by 1 from the expected answer of 8153*7533=61,416,589. The fact that it printed out decimal precision was a hint, and pointed me to the following lines:

https://github.com/Lyken17/pytorch-OpCounter/blob/1ede8b613c13808d9f52ce5666a18922972592be/thop/profile.py#L72-L76

Since the above value is greater than 2^(24) = 16,777,216, it may not be perfectly represented in 32-bit floating-point format.  Indeed, while `p.numel() = 61416549`, `torch.Tensor([p.numel()]).dtype` is `torch.float32`, so the value gets rounded to `tensor([61416548.])`.

Total trainable parameters should probably be stored in variables with an explicit `dtype=torch.int64`.

**Comment by Lyken17** [comment]
That's a good observation! Thanks for pointing it out.

**Comment by Lyken17** [comment]
Fixed in the latest commit.

**Comment by asiltureli** [comment]
I guess the commit related to this topic causes the following error:

File ".../thop/vision/basic_hooks.py", line 27, in count_convNd
    m.total_ops += torch.DoubleTensor([int(total_ops)], dtype=torch.float64)
TypeError: new() received an invalid combination of arguments - got (list, dtype=torch.dtype), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the keywords were incorrect: dtype
 * (object data, torch.device device)
      didn't match because some of the keywords were incorrect: dtype

torch.DoubleTensor already has a datatype of float64 and second parameter is making it crash.

`m.total_ops += torch.DoubleTensor([int(total_ops)]`  
instead of 
`m.total_ops += torch.DoubleTensor([int(total_ops)], dtype=torch.float64)`
 should probably solve the problem.
Thanks for the great job!

**Comment by asiltureli** [comment]
I cloned the repo and saw, that you already fixed it, sorry. I think problem raises, if you install it by using pip. I get this error in the environment, where I installed with pip.

**Comment by Lyken17** [comment]
@asiltureli Thanks for telling me this. I have just uploaded a new release to pip, which should fix the problem.

**Comment by Lyken17** [comment]
The issue should be fixed now. Feel free to re-open it if you have more questions.
